[tools]
committed = "latest"
pre-commit = "latest"
just = "latest"

docker = "latest"

curlie = "latest"

[tasks]
start-apm-test-agent = { dir = "{{config_root}}/testing", run = 'docker compose -f docker-compose.yaml up -d' }
stop-apm-test-agent = { dir = "{{config_root}}/testing", run = 'docker compose -f docker-compose.yaml down' }
start-session = { dir = "{{config_root}}", run = 'curlie http://localhost:8126/test/session/start?test_session_token=doggo' }
snapshot-session = { dir = "{{config_root}}", run = 'curlie http://localhost:8126/test/session/snapshot?test_session_token=doggo' }

[hooks]
enter = "mise i && pre-commit install"

[settings]
experimental = true
lockfile = true
