[workspace]
publish = true
semver_check = true
dependencies_update = false
changelog_update = true
git_release_enable = true
git_tag_enable = true

[[package]]
name = "dogdata"
changelog_path = "crates/dogdata/CHANGELOG.md"
git_tag_name = "dogdata_v{{version}}"

[[package]]
name = "dogdata-reqwest-middleware"
changelog_path = "crates/dogdata/CHANGELOG.md"
git_tag_name = "dogdata-reqwest-middleware_v{{version}}"

[changelog]
protect_breaking_commits = true
sort_commits = "newest"
