services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ddapm:
    image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:latest
    ports:
      - 8126:8126
    environment:
      - SNAPSHOT_CI=0
      - LOG_LEVEL=DEBUG
      - SNAPSHOT_IGNORED_ATTRS=""
    volumes:
      - $PWD/tests/snapshots:/snapshots

volumes:
  postgres_data:
